# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  CI:
    env:
      SERVER_PORT: ${{ secrets.PORT }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.7.0]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Dependencies Installation
      run: npm ci
    
    - name: test
      run: npm run cover
